CREATE TABLE ASSISTS (
  EmployeeID VARCHAR(20) NOT NULL,
  CustomerID VARCHAR(20) NOT NULL,
  PRIMARY KEY (EmployeeID, CustomerID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);