CREATE TABLE CONTAINS (
  OrderID VARCHAR(20) NOT NULL,
  BookID VARCHAR(20) NOT NULL,
  Quantity INT,
  Price FLOAT,
  PRIMARY KEY (OrderID, BookID),
  FOREIGN KEY (OrderID) REFERENCES `ORDER`(OrderID),
  FOREIGN KEY (BookID) REFERENCES BOOK_WITH_INVENTORY(BookID)
);