CREATE TABLE CUSTOMERS (
  CustomerID VARCHAR(20) NOT NULL UNIQUE,
  Street VARCHAR(50),
  City VARCHAR(30),
  State VARCHAR(30),
  Zip VARCHAR(5),
  CFname VARCHAR(15) NOT NULL,
  CLname VARCHAR(15) NOT NULL,
  Email VARCHAR(50),
  PRIMARY KEY (CustomerID)
);



