CREATE TABLE CUSTOMER_PHONENUM (
  CustomerID VARCHAR(20) NOT NULL,
  CPhone_Num VARCHAR(15) NOT NULL,
  PRIMARY KEY (CustomerID, CPhone_Num),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID)
);
