CREATE TABLE MANAGES (
  EmployeeID VARCHAR(20) NOT NULL,
  BookID VARCHAR(20) NOT NULL,
  PRIMARY KEY (EmployeeID, BookID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (BookID) REFERENCES BOOK_WITH_INVENTORY(BookID)
);