CREATE TABLE `ORDER` (
  OrderID VARCHAR(20) NOT NULL UNIQUE,
  ShippingDate DATE,
  PaymentStatus VARCHAR(15) NOT NULL,
  OrderDate DATE,
  ShippingAddress VARCHAR(150) NOT NULL,
  CustomerID VARCHAR(20) NOT NULL,
  PaymentID VARCHAR(20) NOT NULL,
  PRIMARY KEY (OrderID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID),
  FOREIGN KEY (PaymentID) REFERENCES PAYMENTS(PaymentID)
);