CREATE TABLE PROCESSES (
  EmployeeID VARCHAR(20) NOT NULL,
  OrderID VARCHAR(20) NOT NULL,
  PRIMARY KEY (EmployeeID, OrderID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID),
  FOREIGN KEY (OrderID) REFERENCES `ORDER`(OrderID)
);