CREATE TABLE WRITES (
  AuthorID VARCHAR(20) NOT NULL,
  BookID VARCHAR(20) NOT NULL,
  PRIMARY KEY (AuthorID, BookID),
  FOREIGN KEY (AuthorID) REFERENCES `AUTHORS`(AuthorID),
  FOREIGN KEY (BookID) REFERENCES BOOK_WITH_INVENTORY(BookID)
);